// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA56p47zMPJR--r9YSJdbRQ3Al3pq0eEVs',
    appId: '1:337933618419:web:6a4646f22613b29ed27b86',
    messagingSenderId: '337933618419',
    projectId: 'employee-db-76cb0',
    authDomain: 'employee-db-76cb0.firebaseapp.com',
    databaseURL: 'https://employee-db-76cb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-76cb0.firebasestorage.app',
    measurementId: 'G-B4X3N5P29B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLSewWWJIquqwkpy8OEf9Xq7fskQHFd8s',
    appId: '1:337933618419:android:3b2a30e0d19774c8d27b86',
    messagingSenderId: '337933618419',
    projectId: 'employee-db-76cb0',
    databaseURL: 'https://employee-db-76cb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-76cb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWBUIoqxURMSSOIW84SLcuqBxSVSomg8',
    appId: '1:337933618419:ios:4ae565a268eb9ee5d27b86',
    messagingSenderId: '337933618419',
    projectId: 'employee-db-76cb0',
    databaseURL: 'https://employee-db-76cb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-76cb0.firebasestorage.app',
    iosBundleId: 'com.example.employeeMichaeljovanco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYWBUIoqxURMSSOIW84SLcuqBxSVSomg8',
    appId: '1:337933618419:ios:4ae565a268eb9ee5d27b86',
    messagingSenderId: '337933618419',
    projectId: 'employee-db-76cb0',
    databaseURL: 'https://employee-db-76cb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-76cb0.firebasestorage.app',
    iosBundleId: 'com.example.employeeMichaeljovanco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA56p47zMPJR--r9YSJdbRQ3Al3pq0eEVs',
    appId: '1:337933618419:web:5b1e1102ea51d0a3d27b86',
    messagingSenderId: '337933618419',
    projectId: 'employee-db-76cb0',
    authDomain: 'employee-db-76cb0.firebaseapp.com',
    databaseURL: 'https://employee-db-76cb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-76cb0.firebasestorage.app',
    measurementId: 'G-HJQX4C7C7Y',
  );
}
